#! /bin/bash
# ./[deploy|run|stop]CDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>

DNS_SERVER=cs5700cdnproject.ccs.neu.edu
LOGIN_SERVER=login.ccs.neu.edu

KEYFILE=~/.ssh/id_rsa

PORT=40015
ORIGIN=ec2-54-167-4-20.compute-1.amazonaws.com
NAME=cs5700cdn.example.com
USERNAME=wuhao
HOSTS_TEXT_NAME="hosts.txt"

# only username and keyfile is required
while getopts "p::o::u:n::i:" opt; do
    case $opt in
        p)
        PORT=$OPTARG        
        ;;

        o)
        ORIGIN=$OPTARG
        ;;

        n)
        NAME=$OPTARG
        ;;

        u)
        USERNAME=$OPTARG
        ;;

        i)
        KEYFILE=$OPTARG
        ;;

        \?)
        echo "Invalid option: -$OPTARG"
        ;;
esac
done


echo "port:" $PORT
echo "origin:" $ORIGIN
echo "name:" $NAME
echo "username" $USERNAME
echo "keyfile:" $KEYFILE

mkdir logs

# stopping to dns server
DNS_DIR="/home/$USERNAME/cdn"
echo "----------Stop DNS server-----------------------------------------"
echo $DNS_DIR

ssh -i $KEYFILE $USERNAME@$DNS_SERVER "killall -9 dnsserver"
scp -i $KEYFILE $USERNAME@$DNS_SERVER:$DNS_DIR/*.log ./logs

# stopping http servers
# HTTP_DIR="/home/$USERNAME/cdn"
HTTP_DIR="~/"
echo "----------Stop HTTP server----------------------------------------"
echo $HTTP_DIR

while read -r SERVER
do
    echo $SERVER

    # the var that holds the run httpserver command
    CMD="killall -9 httpserver"
    echo $CMD
    scp -i $KEYFILE $USERNAME@$SERVER:~/*.log ./logs

    ssh -n -i $KEYFILE $USERNAME@$SERVER "$CMD;rm -r cache/;rm *;"
done < "hosts.txt"